---
- hosts: local
  become: true

  tasks:
    - name: systmem info
      debug:
        msg: "OS family: {{ ansible_os_family }}, package manager: {{ ansible_pkg_mgr }}"

    - name: install updates
      package:
        name: "*"
        state: latest
    - name: Install additonal packages
          yum: pkg={{item}} state=installed
          with_items:
            - vsftpd
            - xinetd
            - ypserv
            - telnet-server
            - nrpe
            - nagios-server
